/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2022-06-07 01:03:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import bean.User;

public final class listUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.User");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

ArrayList<User> user_list = (ArrayList<User>)request.getAttribute("user_list");



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>ユーザー一覧</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 align=\"center\">書籍管理システムweb版ver.3.0</h1>\r\n");
      out.write("\t<hr align=\"center\" size=\"5\" color=\"blue\" width=\"950\"></hr>\r\n");
      out.write("\t<table align=\"center\" width=\"850\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"80\">[<a\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/view/menu.jsp\">メニュー</a>]\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"80\">[<a\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/view/insertUser.jsp\">ユーザー登録</a>]\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"508\" align=\"center\"><font size=\"5\">ユーザー一覧</font></td>\r\n");
      out.write("\t\t\t<td width=\"80\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td width=\"80\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t<hr align=\"center\" size=\"2\" color=\"black\" width=\"950\"></hr>\r\n");
      out.write("\r\n");
      out.write("\t<table align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/listUser\">\r\n");
      out.write("\t\t\t\t\tユーザー<input type=text size=\"30\" name=\"searchUserid\">\r\n");
      out.write("\t\t\t\t\t <input type=\"submit\" name=\"search\" value=\"検索\"></input>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/listUser\">\r\n");
      out.write("\t\t\t\t\t<input type=hidden size=\"30\" name=\"selectAll\">\r\n");
      out.write("\t\t\t\t\t <input type=\"submit\" name=\"selectAll\" value=\"全件検索\"></input>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th bgcolor=\"#6666ff\" width=\"200\">ユーザー</th>\r\n");
      out.write("\t\t\t<th bgcolor=\"#6666ff\" width=\"450\">Email</th>\r\n");
      out.write("\t\t\t<th bgcolor=\"#6666ff\" width=\"100\">権限</th>\r\n");
      out.write("\t\t\t<th bgcolor=\"#6666ff\" width=\"200\" colspan=\"2\">変更/削除</th>\r\n");
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			if (user_list != null) {
				for (int i = 0; i < user_list.size(); i++) {
					User user = (User) user_list.get(i);

					if(user.getAuthority().equals("1")){
						user.setAuthority("一般ユーザー");
					}else{
						user.setAuthority("管理者");
					}
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"200\" ><a href=\"");
      out.print( request.getContextPath() );
      out.write("/detailUser?userid=");
      out.print(user.getUserid() );
      out.write("&param=detail\">\r\n");
      out.write("\t\t\t");
      out.print(user.getUserid() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"450\" >");
      out.print(user.getEmail() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"100\" >");
      out.print(user.getAuthority() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"200\"  colspan=\"2\" >\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( request.getContextPath() );
      out.write("/detailUser?param=update&userid=");
      out.print(user.getUserid());
      out.write("\">変更</a>\r\n");
      out.write("\t\t\t<a id=\"btn\" href=\"");
      out.print( request.getContextPath() );
      out.write("/deleteUser?userid=");
      out.print(user.getUserid());
      out.write("\">削除</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
			} else {
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"200\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"200\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"200\">&nbsp;</td>\r\n");
      out.write("\t\t\t<td align=\"center\" width=\"250\" colspan=\"2\">&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<hr align=\"center\" size=\"5\" color=\"blue\" width=\"950\"></hr>\r\n");
      out.write("\r\n");
      out.write("\t<table border=0 align=\"center\" width=\"950\" summary=\"フッター表示\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>copyright (c) 2010 all rights reserved.</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
